vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|03 Jun 2008 15:41:10 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{C11A800C-CD2D-44E2-84B0-F90FDC61CF3D}
vti_backlinkinfo:VX|
vti_author:SR|LASA-WPCF\\brianb
vti_modifiedby:SR|LASA-WPCF\\brianb
vti_nexttolasttimemodified:TW|11 Oct 2006 18:16:48 -0000
vti_timecreated:TR|03 Jun 2008 15:41:10 -0000
vti_cacheddtm:TX|03 Jun 2008 15:41:10 -0000
vti_filesize:IR|12245
vti_syncwith_172.18.10.61\:80:TR|03 Jun 2008 15:41:10 -0000
