vti_encoding:SR|utf8-nl
vti_author:SR|LASA-WPCF\\brianb
vti_modifiedby:SR|LASA-WPCF\\brianb
vti_timelastmodified:TR|09 Nov 2007 19:42:18 -0000
vti_timecreated:TR|13 Jun 2007 12:57:23 -0000
vti_title:SR|New Page 1
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{9085CC7D-7F37-4FDD-A73C-84EC3F244420}
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|09 Nov 2007 19:37:40 -0000
vti_cacheddtm:TX|09 Nov 2007 19:42:18 -0000
vti_filesize:IR|1663
vti_syncwith_172.18.10.61\:80:TR|09 Nov 2007 19:42:18 -0000
