<script type="text/javascript" language="JavaScript1.2">
<!--
stm_bm(["menu3645",660,"inc","blank.gif",0,"","",0,0,250,0,1000,1,0,1,"","",0,0,1,2,"default","hand",""],this);
stm_bp("p0",[1,4,0,0,2,3,0,7,100,"",-2,"",-2,50,0,0,"#999999","#FFFFF7","corbkgnd.gif",3,0,0,"#000000"]);
stm_ai("p0i0",[0,"Project Options","","",-1,-1,0,"","_self","","","","",0,0,0,"arrow_r.gif","arrow_r.gif",7,7,0,0,1,"#FFFFF7",1,"#B5BED6",0,"","",3,3,0,0,"#FFFFF7","#000000","#0000CC","#0000CC","bold 8pt Tahoma","bold 8pt Tahoma",0,0]);
stm_bpx("p1","p0",[1,2,0,0,2,3,0,0,100,"",-2,"",-2,50,0,0,"#999999","#FFFFF7","corbkgnd.gif",3,1,1]);
stm_aix("p1i0","p0i0",[0,"View Notes","","",-1,-1,0,"javascript:comments()","_self","","","","",0,0,0,"","",0,0]);
stm_aix("p1i1","p1i0",[0,"Capacity Reserve WorkSheet","","",-1,-1,0,"javascript:crp_ws()"]);
stm_aix("p1i2","p1i0",[0,"Permit WorkSheet","","",-1,-1,0,"Permit_WorkSheet.asp?PID=<%=PID%>","ibody"]);
stm_aix("p1i3","p1i2",[0,"Open Permits","","",-1,-1,0,"Permit_Open.asp?PID=<%=PID%>"]);
stm_aix("p1i4","p1i2",[0,"Closed Permits","","",-1,-1,0,"Permit_Closed.asp?Pid=<%=PID%>"]);
stm_aix("p1i5","p1i0",[0,"Edit Project Information","","",-1,-1,0,"javascript:part1()"]);
stm_aix("p1i6","p1i0",[0,"Edit Contact Information","","",-1,-1,0,"javascript:part2()"]);
stm_aix("p1i7","p1i2",[0,"Service Request WorkSheet","","",-1,-1,0,"javascript:srl_ws()"]);
stm_aix("p1i8","p1i2",[0,"Project Table Fix","","",-1,-1,0,"javascript:table_fix()"]);
stm_aix("p1i8","p1i2",[0,"On-Lot Septic Editor","","",-1,-1,0,"javascript:OLS_Edit()"]);
stm_ep();
stm_ep();
stm_cf([2,0,0,"main","header",1]);
stm_em();
//-->
</script>
